# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_time_from_intervals": "01_simulations.ipynb"}

modules = ["simulations.py"]

doc_url = "https://abhishekshar.github.io/pp_lvm/"

git_url = "https://github.com/abhishekshar/pp_lvm/tree/master/"

def custom_doc_links(name): return None
