# AUTOGENERATED! DO NOT EDIT! File to edit: 01_simulations.ipynb (unless otherwise specified).

__all__ = ['get_time_from_intervals']

# Cell
def get_time_from_intervals(I):
    last_dim_size = I.shape[-1]
    I = F.pad(I, (1,0)) #pads the last dimension with width=1 on the left and width=0 on the right. Value of padding=0
    I = I.cumsum(dim=-1)
    # Note: new I has one element extra than initial I on the final dimension. This cuts that one last element in a general way
    I = torch.stack([torch.select(I, I.dim()-1, i) for i in range(last_dim_size)], dim=-1)
    return I